version: 2
updates:
- package-ecosystem: nuget
  directory: "/src/Plugins/Components.Support"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/src/Components/TagPickerComponent"
  schedule:
    interval: daily
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.41
    - 15.0.0
  - dependency-name: office-ui-fabric-react
    versions:
    - 7.168.0
    - 7.168.1
  - dependency-name: ssri
    versions:
    - 6.0.2
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
- package-ecosystem: npm
  directory: "/src/Components/TagPickerGridComponent"
  schedule:
    interval: daily
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.41
    - 15.0.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
