# Whether to take any action when records are detected in the cache paths that don't map to evaluated
# dependencies.
# Available values are:
# - 'error': treat stale cached records as errors.  Notify the user and fail status checks
# - 'warn', '', unset: treat stale cached records as warnings.  Notify the user but do not fail status checks
# - 'ignore': Ignore stale cached records.  Do not notify the user and do not fail status checks
# Optional, when not set this defaults to 'warn' behavior
stale_records_action: "warn"

# Sources of metadata
sources:
  npm: true
  nuget: true

# Dependencies with these licenses are allowed and will not raise errors or warnings.
# This list does not have a default value and is required for `licensed status`
# to succeed.
allowed:
  - isc
  - mit
  - 0bsd

# These dependencies have licenses not on the `allowed` list and have been reviewed.
# They will be cached and checked, but will not raise errors or warnings for a
# non-allowed license.  Dependencies on this list will still raise errors if
# license text cannot be found for the dependency.
reviewed:
  npm:
    - "@fluentui/date-time-utilities" # mit
    - "@fluentui/dom-utilities" # mit
    - "@fluentui/keyboard-key" # mit
    - "@fluentui/react-focus" # mit
    - "@fluentui/react-stylesheets" # mit
    - "@fluentui/react-theme-provider" # mit
    - "@fluentui/react-window-provider" # mit
    - "@fluentui/theme" # mit
    - "@microsoft/load-themed-styles" # mit
    - "@uifabric/foundation" # mit
    - "@uifabric/icons" # mit
    - "@uifabric/merge-styles" # mit
    - "@fluentui/react-compose" # mit
    - "@uifabric/react-hooks" # mit
    - "@uifabric/set-version" # mit
    - "@uifabric/styling" # mit
    - "@uifabric/utilities" # mit
    - "office-ui-fabric-react" # mit
    - "lodash" # CC0-1.0

# A single configuration file can be used to enumerate dependencies for multiple
# projects.  Each configuration is referred to as an "application" and must include
# a source path, at a minimum
apps:
  - source_path: src/Components/TagPickerComponent
  - source_path: src/Components/TagPickerGridComponent
  - source_path: src/Components/TaskManagerComponent
  - source_path: src/Components/TreeComponent
  - source_path: src/Plugins/Components.Support/obj
  - source_path: src/Plugins/Components.Support.Tests/obj
