#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# cd TagPickerComponent
# npx lint-staged

# cd ../TagPickerGridComponent
# npx lint-staged

# cd ../TaskManagerComponent
# npx lint-staged

cd src/Components/TreeComponent
npx lint-staged