name: Generate license files for each projects

on:
  push:
    branches: [features/licenses]
jobs:
  build:
      name: Set-up
      runs-on: ubuntu-latest
      steps:
        - name: Install license-checker
          run: npm install -g license-checker
  generate-license-file:
    name: Generate license files
    uses: opc-cpvp/OPC.PowerApps.PCFControls/.github/workflows/licenses.yml@features/licenses
    with: 
      directory: TagPickerComponent