name: Create License File

on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: string

jobs:
  build:
    name: Called workflow
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/Components/${{ inputs.directory }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install license-checker
        run: npm install -g license-checker
      - name: Install packages
        run: npm install
      - name: Generate license file for ${{ inputs.directory }}
        run: license-checker --production > license.txt
      - name: Check for modified files
        id: git-status
        run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)
      - name: Update changes
        if: steps.git-status.outputs.modified == 'true'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m 'Add license file using Create License file GitHub Workflow'
          git push