name: Generate license files

on: [push]
jobs:
  license_components:
    name: Generate licenses for components
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        directories: [TagPickerComponent,TagPickerGridComponent,TaskManagerComponent,TreeComponent]
    defaults:
      run:
        working-directory: ./src/Components/${{ matrix.directories }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install packages
        run: npm install
      - name: Install license-checker
        run: npm install -g license-checker
      - name: Generate license file
        run: license-checker --production > 'license.txt'
      - name: Update changes
        uses: EndBug/add-and-commit@v8
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: '[Automated] Added license file'
          cwd: './src/Components/${{ matrix.directories }}'
          add: 'license.txt'
          push: false
      - name: Push changes
        run: |
          git pull --rebase
          git push
  license_plugins:
    name: Generate licenses for plugins
    runs-on: ubuntu-latest
    needs: license_components
    defaults:
      run:
        working-directory: ./src/Plugins/Components.Support
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install nuget-license
        run: dotnet tool install --global dotnet-project-
      - name: Generate license file
        run: dotnet-project-licenses -i . -o  --outfile 'license.txt'
      - name: Update changes
        uses: EndBug/add-and-commit@v8
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: '[Automated] Added license file'
          cwd: './src/Plugins/Components.Support'
          add: 'license.txt'
