name: Generate license files

on: [pull_request]
jobs:
  build:
    name: Generate license file
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directories: [TagPickerComponent,TagPickerGridComponent,TaskManagerComponent,TreeComponent]
    defaults:
      run:
        working-directory: ./src/Components/${{ matrix.directories }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
         with:
          ref: ${{ github.head_ref }}
      - name: Install license-checker
        run: npm install -g license-checker
      - name: Install packages
        run: npm install
      - name: Generate license file for ${{ matrix.directory }}
        run: license-checker --production > license.txt
      - name: Check for modified files
        id: git-status
        run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)
      - name: Update changes
        if: steps.git-status.outputs.modified == 'true'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m 'Add license file using Create License file GitHub Workflow'
          git push