name: Generate license files

on: [push]
jobs:
  build:
    name: Generate license file
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directories: [TagPickerComponent,TagPickerGridComponent]
    defaults:
      run:
        working-directory: ./src/Components/${{ matrix.directories }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install packages
        run: npm install
      - name: Install license-checker
        run: npm install -g license-checker
      - name: Generate license file
        run: license-checker --production > 'license.txt'
      - name: Status 1
        run: echo $(git status --porcelain)
      
  add:
    name: Add file to repository
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Status 2
        run: echo $(git status --porcelain)
      - name: Update changes
        uses: EndBug/add-and-commit@v8
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: '[Automated] Added license file'
          add: '*.txt'
