# The following parameters need to be set when the task is queued to run:
# environmentUrl: The URL of the environment where you want to deploy.

parameters:
  - name: environment
    type: string

steps:
  - template: 'install-solution.yml'
    parameters:
      environment: ${{ parameters.environment }}
