# The following parameters need to be set when the task is queued to run:
# environmentUrl: The URL of the environment where you want to install.

parameters:
- name: environment
  type: string

steps:
- task: DownloadPipelineArtifact@2
  displayName: 'Download Build Pipeline Artifact'

- powershell: |
   $artifactDropPath = '$(Pipeline.Workspace)\drop'
   If (Test-Path -Path "$(Pipeline.Workspace)\buildPipeline\drop")
   {
       $artifactDropPath = "$(Pipeline.Workspace)\buildPipeline\drop"
   }
   Write-Host "##vso[task.setVariable variable=ArtifactDropPath]$artifactDropPath"
  displayName: 'Get artifact drop path'

- task: PowerPlatformToolInstaller@2
  displayName: 'Install Power Tools'
  inputs:
    DefaultVersion: true

- task: PowerPlatformImportSolution@2
  displayName: 'Deploy PCF Solution'
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: 'PowerApps - ${{ parameters.environment }} - Package Deployer Service'
    Environment: 'https://priv360-${{ parameters.environment }}.crm3.dynamics.com/'
    SolutionInputFile: '$(ArtifactDropPath)\src\Solution\bin\Release\Solution_managed.zip'
    AsyncOperation: true
    MaxAsyncWaitTime: '60'
    OverwriteUnmanagedCustomizations: true
