trigger: none
pr: none

resources:
  pipelines:
    - pipeline: buildPipeline
      source: 'OPC.PowerApps.PCFControls - CI'

parameters:
  - name: environment
    displayName: 'Environment'
    type: string
    values:
     - 'SprintEven'
     - 'SprintOdd'
     - 'Dev'

variables:
  - group: 'prod-tenant-dev'

stages:
- stage: deploy
  displayName: 'Deploy'
  jobs:
  - job: deploy_job
    pool:
      vmImage: 'windows-2019'
    timeoutInMinutes: 120
    steps:
    - download: buildPipeline
    - template: 'templates\deploy-solution.yml'
      parameters:
        environment: ${{ parameters.environment }}