trigger: none
pr: none

resources:
  pipelines:
    - pipeline: buildPipeline
      source: 'OPC.PowerApps.PCFControls - CI'
      trigger:
        branches:
          include:
          - master

variables:
  - group: prod-tenant

stages:
  - stage: release
    displayName: 'Release to GitHub'
    jobs:
    - deployment:
      pool:
        vmImage: 'windows-2019'
      timeoutInMinutes: 120
      environment: 'GitHub'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: 'templates\release-solution.yml'